### ISSUE TITLE
Scope of this repo?

### ISSUE THREAD

**Issue by dumblob** [vincenzopalazzo/benchmarks#2]
Is the goal of this repo to only perform Google benchmarks or rather "benchmark V in any imaginable way to find bottle necks, their culprits, and (potential) solutions"?

If the latter, I would file an issue to investigate the non-performance of `-prod` builds on [kostya's machine](https://github.com/kostya/benchmarks/#benchb ) (or in other words why Go is as fast as C on that machine and not on some other machines as discussed in https://github.com/vlang/v/discussions/14222#discussioncomment-2732867 ).

Could the scope of this repo be documented in readme?

**Comment by vincenzopalazzo** [comment]
>Google benchmarks 

Google benchmark is the minimum common divisor between languages because you can use a single library for all the algorithms written in different languages, this avoid also to implement a very stupid benchmark with "end - start" time, but there are well tested euristic implemented by the lib.

>If the latter, I would file an issue to investigate the non-performance of -prod builds on [kostya's machine](https://github.com/kostya/benchmarks/#benchb) (or in other words why Go is as fast as C on that machine and not on some other machines as discussed in https://github.com/vlang/v/discussions/14222#discussioncomment-2732867 ).

Run the benchmark with `-prod` can be an option too

> Could the scope of this repo be documented in readme?

The scope of the readme is all the useful benchmarks written with a good style and how a real code is written between languages.

I don't want include unuseful example, or only language specific example! So if this is your goal I think this repo is not for you, otherwise contributors are welcome, but the code need to be well written
